language: erlang
otp_release:
  # Not available on Travis CI: 19.1, 19.2 and 20.2
  - 19.0
  - 19.3
  - 20.0
  - 20.1
  - 20.3
  - 21.0
  - 21.1.7
  - 21.2
  - 21.3
  - 22.0
  - 22.1
  - 22.2
  - 22.3
  - 23.0

env:
  - TEST=1

before_script:
    - kerl list installations
    - "gunicorn -b 127.0.0.1:8000 -b unix:httpbin.sock httpbin:app&"

before_install:
  - sudo pip install -q httpbin
  - sudo pip install -q gunicorn

script:
  - ./support/rebar3 eunit
  - ./support/rebar3 dialyzer

cache:
  directories:
    - $HOME/.cache/rebar3
